services:
  backend:
    build:
      context: ./backend/TodoApi
      dockerfile: Dockerfile
    ports:
      - "5140:5140"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
